name: CI

on:
  pull_request:
    branches:
      - master
    paths:
      - "pages/**"

jobs:
  condition:
    name: Check Lint & Test Condition
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "16.14.x"
          check-latest: true

      - name: Install Dependencies
        run: yarn install

      - name: Run Next Lint
        run: yarn lint

      - name: Run tests with jest
        run: yarn test:ci

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [condition]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "16.14.x"
          check-latest: true

      - name: Install Dependencies
        run: yarn install

      - name: Run build
        run: yarn build
